"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-28 14:09:31.633424
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '0001'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('prefix', sa.String(length=32), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('scopes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('allowed_principals', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_created_at'), 'api_keys', ['created_at'], unique=False)
    op.create_index('ix_api_keys_prefix', 'api_keys', ['prefix'], unique=True)
    op.create_index('ix_api_keys_revoked', 'api_keys', ['revoked_at'], unique=False)
    op.create_table('audit_records',
    sa.Column('seq', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('record_hash', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('seq'),
    sa.UniqueConstraint('record_hash'),
    sa.UniqueConstraint('seq', name='uq_audit_records_seq')
    )
    op.create_index('ix_audit_records_actor', 'audit_records', ['actor'], unique=False)
    op.create_index('ix_audit_records_event_ts', 'audit_records', ['event', 'timestamp'], unique=False)
    op.create_index('ix_audit_records_subject', 'audit_records', ['subject'], unique=False)
    op.create_index(op.f('ix_audit_records_timestamp'), 'audit_records', ['timestamp'], unique=False)
    op.create_table('data_assets',
    sa.Column('urn', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('urn', name='uq_data_assets_urn')
    )
    op.create_index(op.f('ix_data_assets_created_at'), 'data_assets', ['created_at'], unique=False)
    op.create_index('ix_data_assets_kind', 'data_assets', ['kind'], unique=False)
    op.create_index('ix_data_assets_owner', 'data_assets', ['owner'], unique=False)
    op.create_table('decisions',
    sa.Column('principal_id', sa.String(length=255), nullable=False),
    sa.Column('principal_type', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_urn', sa.String(length=512), nullable=False),
    sa.Column('resource_kind', sa.String(length=64), nullable=False),
    sa.Column('effect', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('determining_policy', sa.String(length=128), nullable=True),
    sa.Column('matched_policies', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('obligations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('classifications', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('finding_count', sa.Integer(), nullable=False),
    sa.Column('redaction_count', sa.Integer(), nullable=False),
    sa.Column('payload_digest', sa.String(length=64), nullable=True),
    sa.Column('context', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('trace', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('correlation_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_correlation_id'), 'decisions', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_decisions_created_at'), 'decisions', ['created_at'], unique=False)
    op.create_index('ix_decisions_effect_created', 'decisions', ['effect', 'created_at'], unique=False)
    op.create_index('ix_decisions_principal_created', 'decisions', ['principal_id', 'created_at'], unique=False)
    op.create_index('ix_decisions_resource', 'decisions', ['resource_urn'], unique=False)
    op.create_table('policies',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('effect', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('document', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_policies_key')
    )
    op.create_index(op.f('ix_policies_created_at'), 'policies', ['created_at'], unique=False)
    op.create_index('ix_policies_enabled_priority', 'policies', ['enabled', 'priority'], unique=False)
    op.create_table('principals',
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id', name='uq_principals_external_id')
    )
    op.create_index(op.f('ix_principals_created_at'), 'principals', ['created_at'], unique=False)
    op.create_index('ix_principals_type_disabled', 'principals', ['type', 'disabled_at'], unique=False)
    op.create_table('approval_requests',
    sa.Column('decision_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_by', sa.String(length=255), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('decided_by', sa.String(length=255), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_id')
    )
    op.create_index(op.f('ix_approval_requests_created_at'), 'approval_requests', ['created_at'], unique=False)
    op.create_index('ix_approval_status_created', 'approval_requests', ['status', 'created_at'], unique=False)
    op.create_table('asset_classifications',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('asserted_by', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['data_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'label', 'source', name='uq_asset_label_source')
    )
    op.create_index(op.f('ix_asset_classifications_asset_id'), 'asset_classifications', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_classifications_created_at'), 'asset_classifications', ['created_at'], unique=False)
    op.create_index('ix_asset_classifications_label', 'asset_classifications', ['label'], unique=False)
    op.create_table('policy_versions',
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('policy_key', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('document', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=False),
    sa.Column('changed_by', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_id', 'version', name='uq_policy_versions_policy_version')
    )
    op.create_index(op.f('ix_policy_versions_created_at'), 'policy_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_policy_versions_policy_id'), 'policy_versions', ['policy_id'], unique=False)
    op.create_index(op.f('ix_policy_versions_policy_key'), 'policy_versions', ['policy_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_versions_policy_key'), table_name='policy_versions')
    op.drop_index(op.f('ix_policy_versions_policy_id'), table_name='policy_versions')
    op.drop_index(op.f('ix_policy_versions_created_at'), table_name='policy_versions')
    op.drop_table('policy_versions')
    op.drop_index('ix_asset_classifications_label', table_name='asset_classifications')
    op.drop_index(op.f('ix_asset_classifications_created_at'), table_name='asset_classifications')
    op.drop_index(op.f('ix_asset_classifications_asset_id'), table_name='asset_classifications')
    op.drop_table('asset_classifications')
    op.drop_index('ix_approval_status_created', table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_created_at'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index('ix_principals_type_disabled', table_name='principals')
    op.drop_index(op.f('ix_principals_created_at'), table_name='principals')
    op.drop_table('principals')
    op.drop_index('ix_policies_enabled_priority', table_name='policies')
    op.drop_index(op.f('ix_policies_created_at'), table_name='policies')
    op.drop_table('policies')
    op.drop_index('ix_decisions_resource', table_name='decisions')
    op.drop_index('ix_decisions_principal_created', table_name='decisions')
    op.drop_index('ix_decisions_effect_created', table_name='decisions')
    op.drop_index(op.f('ix_decisions_created_at'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_correlation_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index('ix_data_assets_owner', table_name='data_assets')
    op.drop_index('ix_data_assets_kind', table_name='data_assets')
    op.drop_index(op.f('ix_data_assets_created_at'), table_name='data_assets')
    op.drop_table('data_assets')
    op.drop_index(op.f('ix_audit_records_timestamp'), table_name='audit_records')
    op.drop_index('ix_audit_records_subject', table_name='audit_records')
    op.drop_index('ix_audit_records_event_ts', table_name='audit_records')
    op.drop_index('ix_audit_records_actor', table_name='audit_records')
    op.drop_table('audit_records')
    op.drop_index('ix_api_keys_revoked', table_name='api_keys')
    op.drop_index('ix_api_keys_prefix', table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_created_at'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
